package org.urlshortener.urlshortener.models;


import jakarta.persistence.*;
import lombok.Getter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Base JPA model for entities in the UrlShortener application.
 *
 * <p>This mapped superclass provides a shared primary key and audit timestamps
 * for concrete entities that extend it.</p>
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
public class BaseModel {
    /**
     * Surrogate primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", nullable = false)
    private Long id;

    /**
     * Timestamp when the entity was created.
     * Populated when Spring Data JPA auditing is enabled.
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp when the entity was last updated.
     * Populated when Spring Data JPA auditing is enabled.
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;
}
